name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Set AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.YC_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.YC_SECRET_KEY }}" >> $GITHUB_ENV
          echo "YC_CLOUD_ID=${{ secrets.YC_CLOUD_ID }}" >> $GITHUB_ENV

      - name: Terraform Init (Backend)
        working-directory: 01-backend
        run: terraform init -backend-config="bucket=diplom-tfstate-relekt" -backend-config="key=backend/terraform.tfstate" -backend-config="region=ru-central1" -backend-config="endpoint=https://storage.yandexcloud.net" -reconfigure

      - name: Terraform Plan (Infrastructure)
        working-directory: 02-infrastructure
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Infrastructure)
        working-directory: 02-infrastructure
        run: terraform apply tfplan
