name: Terraform CI/CD for Yandex Cloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        # Убрали terraform_version: 1.6.7 — такой версии не существует
        uses: hashicorp/setup-terraform@v3

      - name: Set AWS credentials & Terraform variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.YC_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.YC_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_yc_cloud_id=${{ secrets.YC_CLOUD_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_yc_folder_id=${{ secrets.YC_FOLDER_ID }}" >> $GITHUB_ENV

      - name: Terraform Init (Backend)
        run: terraform init -upgrade

      - name: Terraform Plan (Infrastructure)
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Infrastructure)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
