name: Terraform CI/CD for Yandex Cloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # После этого шага файлы репозитория лежат прямо в корне раннера

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set AWS credentials & Terraform variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.YC_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.YC_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_yc_cloud_id=${{ secrets.YC_CLOUD_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_yc_folder_id=${{ secrets.YC_FOLDER_ID }}" >> $GITHUB_ENV

      # Инициализация бэкенда: путь БЕЗ diploma/
      - name: Terraform Init (Backend)
        working-directory: 01-backend
        run: terraform init -upgrade

      # План изменений: путь БЕЗ diploma/
      - name: Terraform Plan (Infrastructure)
        working-directory: 02-infrastructure
        run: terraform plan -out=tfplan

      # Применение изменений
      - name: Terraform Apply (Infrastructure)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: 02-infrastructure
        run: terraform apply -auto-approve tfplan
